version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ~/.local/data/mongodb:/data/db
      - ~/.config/nvim:/root/.config/nvim
      - ~/mongodb:/mongodb
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
