version: "3.8"
services:
  mysql:
    image: mysql:debian
    container_name: mysql
    restart: always
    ports:
      - 3006:3306
    volumes:
      - ~/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
